### PR TITLE
Create mainnet/chris-remus-entity.json

### PR DESCRIPTION
**Pull request by cfl0ws**

### CODE REVIEW

**Comment by hydai** [comment]
Hi, @chris-remus 
Thanks for submitting entity information to us.

Do you want to join the testnet or mainnet?
If you want to join the mainnet, please put your file under the `mainnet` folder. Thanks.

**Comment by cfl0ws** [comment]
@hydai moved the file to mainnet/ thank you!

**Comment by hydai** [comment]
@chris-remus 
Please rebase to the latest master branch. So I can merge your PR.

**Comment by hydai** [comment]
Replaced by #37

**Pull request closed without merging**
