### PR TITLE
add oeth entity for zju-aif

### PR DESCRIPTION
**Pull request by cherideal**

### CODE REVIEW

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Hi @cherideal 
Thanks for submitting your entity information.
We've added your entity id into our ParaTime allowlist. You can join our compute node group now.

**Comment by hydai** [comment]
Hi @cherideal 
After your ParaTime is online, we encountered some consensus issues, could you help us to debug with it?
We will need the following information from your working environment and logs:

1. What is your operating system?
2. Could you upload your node logs, which is at `$DATA_DIR/node.log`, this may be very large but very useful for us to debug.
3. How many ports do you expose? node P2P, gRPC? Or do you let the firewall on?

**Comment by hydai** [comment]
Dear @cherideal  ,
Thanks for submitting the SSVM ParaTime entities.

We are encountering an issue related to the storage state. The consensus will be broken when any new ParaTime joins into the consensus group. That's why your entity is not in the whitelist at this moment.

Fortunately, we figured out the issue and fixed it with the support of the oasis team.
To fix it, we are planning to update the ParaTime settings and software after the hackathon.
We will stop the ParaTime at 10/26 10:00 a.m. (UTC+8), and restart it at 10/26 18:00 p.m (UTC+8) .

After restarting the ParaTime, your entity will be added back to the whitelist. Also, we will update the step-by-step setup guide and video.

My apologies for any inconvenience. And thanks for your patience.

**Comment by MileyFu** [comment]
Dear @cherideal ,

Hello :) it is Miley from Oasis Ethereum. Have you run the updated software yet? If not please make time to do so to get ready before the mainnet launch in February. Details here -> https://link.medium.com/eZ18ZTC4odb

The OasisEth is in its mainnet beta stage right now. After we run the latest release v1.5.2 for a couple of weeks, we will announce the mainnet genesis. If you encounter any kind of problem operating the node please do not hesitate to contact me and the team. Looking forward to hearing from you!

**Pull request merged**
